server:
  port: 8081

spring:
  application:
    name: auth-service

  datasource:
    url: Dummy
    username: Dummy
    password: Dummy
    driver-class-name: com.microsoft.sqlserver.jdbc.SQLServerDriver

  jpa:
    hibernate:
      ddl-auto: update
    show-sql: false

eureka:
  client:
    service-url:
      defaultZone: http://localhost:8761/eureka
