server:
  port: 8080

spring:
  application:
    name: api-gateway
  cloud:
    discovery:
      enabled: true
    gateway:
      discovery:
        locator:
          enabled: false

  datasource:
    url: jdbc:sqlserver://US-PF3JPDEW:1433;DatabaseName=EXPENSE;encrypt=true;trustServerCertificate=true
    username: spring
    password: spring1
    driver-class-name: com.microsoft.sqlserver.jdbc.SQLServerDriver

  jpa:
    hibernate:
      ddl-auto: update
    show-sql: false

eureka:
  client:
    service-url:
      defaultZone: http://localhost:8761/eureka
