server:
  port: 8083

spring:
  application:
    name: financeservice
  datasource:
    url: Dummy
    username: Dummy
    password: Dummy
    driver-class-name: com.microsoft.sqlserver.jdbc.SQLServerDriver

  logging:
    level:
      com.financeservice.service.Dashboard.clients: DEBUG
  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true


eureka:
  client:
    service-url:
      defaultZone: http://localhost:8761/eureka

