server:
  port: 8082

spring:
  application:
    name: expense-category-service

  datasource:
    url: Dummy
    username: Dummy
    password: Dummy
    driver-class-name: com.microsoft.sqlserver.jdbc.SQLServerDriver


  kafka:
    bootstrap-servers: localhost:9092

  jpa:
    hibernate:
      ddl-auto: update
    show-sql: false

 # redis:
  #  host: localhost
   # port: 6379


eureka:
  client:
    service-url:
      defaultZone: http://localhost:8761/eureka
